services:
  web:
    container_name: jasperreports
    image: 8d40ab0e0087
    restart: always  
    depends_on:
      - db
    ports:
      - "9091:8080"
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    environment:
      - JASPERREPORTS_USERNAME=jasperadmin
      - JASPERREPORTS_PASSWORD=jasperadmin
      - JASPERREPORTS_DATABASE_HOST=mariadb
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_PASSWORD=bitnami
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
    networks:
      - default
      - oracle-adb-network
  db:
    container_name: mariadb
    image: bitnami/mariadb:latest
    restart: always  
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_jasperreports
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_jasperreports    
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - default

networks:
  oracle-adb-network:
    external: true

volumes:
  mariadb_data:
  jasperreports_data: